#------------------------------------------------------------------------------
# Builds a neonFORGE GitHub repo solution on a JOBRUNNER within the [C:\src] directory.

name: build
description: "Builds one of the neonFORGE repos with options"
inputs:
  build-branch:
    description: "Specifies the build branch"
    required: true
  build-config: 
    description: "Specifies the build configuration"
    required: false
    default: debug
  build-tools:
    description: "Indicates whether tools should be built and published to the repo's Build folder"
    required: false
    default: "false"
  build-installers:
    description: "Indicates whether installers should be built"
    required: false
    default: "false"
  build-codedoc:
    description: "Indicates whether code documentation should be built"
    required: false
    default: "false"
  build-log:
    description: "Specifies the build log file name"
    required: true
  fail-on-error:
    description: "Fail the activity step for build errors"
    required: false
    default: "true"
outputs:
  success: 
    description: "Returns 'true' on success or 'false' on failure"
  build-branch:
    description: "Returns as the repo branch built"
  build-config:
    description: "Returns as the build configuration"
  build-commit:
    description: "Returns as the git commit hash built"
  build-commit-uri:
    description: "Returns as the GitHub URI to the commit built"
  build-log:
    description: "Returns as the local path to the build log"
runs:
  using: node12
  main: action.js
